export const ENGINE_VERSION = '0.1.0';
export * from './types/index.js';
export type { CacheStore } from './cache/index.js';
export { LruCache } from './cache/index.js';
export { RequestQueue } from './queue/index.js';
export type { QueueConfig, QueueStatus, QueueEventType, QueueEventListener } from './queue/index.js';
export { calculateBackoff } from './queue/index.js';
export type { BackoffConfig } from './queue/index.js';
export { MusicBrainzProvider } from './providers/musicbrainz/index.js';
export type { MusicBrainzProviderOptions } from './providers/musicbrainz/index.js';
export { ListenBrainzProvider } from './providers/listenbrainz/index.js';
export type { ListenBrainzProviderOptions } from './providers/listenbrainz/index.js';
export { LastFmProvider } from './providers/lastfm/index.js';
export type { LastFmProviderOptions } from './providers/lastfm/index.js';
export { DeezerProvider } from './providers/deezer/index.js';
export type { DeezerProviderOptions } from './providers/deezer/index.js';
export { TasteDiveProvider } from './providers/tastedive/index.js';
export type { TasteDiveProviderOptions } from './providers/tastedive/index.js';
export { SpotifyProvider } from './providers/spotify/index.js';
export type { SpotifyProviderOptions } from './providers/spotify/index.js';
export { EntityResolver } from './resolver/index.js';
export type { EntityResolverOptions } from './resolver/index.js';
export type { ArtistCandidate, ResolvedIdentity } from './resolver/index.js';
